### ISSUE TITLE
Currently logged in user

### ISSUE THREAD

**Issue by Jhappy77** [techstartucalgary/tsu-website#157]
There should be a spot on the screen where it shows the currently logged in user. This is very important (visibility of system status is a critical design heuristic)

**Comment by Niyousha99** [comment]
@Jhappy77 Any other requirements to keep in mind for this issue?

**Comment by Jhappy77** [comment]
There should be a good-looking way of showing what user is currently logged in on the community page. Research examples of how this is done on other sites - usually with a little message near the top right of the screen saying "Logged in as X" or "Welcome X", perhaps next to a user icon. This will let users know if they are logged in.

If no one is signed in, it should say a slightly different message, like "Using as guest".

Let us know your thoughts/ideas with a wireframe in the discord!

You can use Postman for API testing if ever necessary.
