### ISSUE TITLE
Blobbies for borders

### ISSUE THREAD

**Issue by Jhappy77** [techstartucalgary/tsu-website#332]
It would be nice to have some blobbies straddling the border between the light and dark sections of the pages.
We will need to change them to be opaque (probably via a prop that you can trigger on and off so this doesn't change the other blobbies)

Be sure to test their positioning and sizing extensively to make sure they don't interfere with page different screen sizes!

**Comment by Smit1610** [comment]
Can you please elaborate what is to be done.  and what type of styling do you want. 
Please share image/video.

**Comment by Niyousha99** [comment]
Won't do
