### ISSUE TITLE
Npm Audit

### ISSUE THREAD

**Issue by Jhappy77** [techstartucalgary/tsu-website#355]
![image](https://user-images.githubusercontent.com/45266424/171791188-ddaca8e7-5acb-4dd4-8b23-1ee6b0cfbaab.png)
Should upgrade packages to fix vulnerabilities. 

May also be worth establishing a recommended version of node/npm for contributors to use, since different versions of npm create different package-lock.json files. Can recommend that people use nvm to manage which version of node they use

Non-windows: https://github.com/nvm-sh/nvm
Windows: https://github.com/coreybutler/nvm-windows

**Comment by Niyousha99** [comment]
Significantly reduced our vulnerabilities - rest to be addressed through dependabot
