### ISSUE TITLE
Add videos for some of the past project teams

### ISSUE THREAD

**Issue by Jhappy77** [techstartucalgary/tsu-website#364]
Some of the teams from last year made videos (but not all of them).

We should look into a way to add their videos to the site on the projects page.
Some ideas:
- A link to the video shows up as a button underneath "Visit Project" 
- Row of button links underneath their respective projects
- Separate part of the projects page has embedded videos

Keep in mind only 2 projects have videos right now. So we can make a call of whether we want to add this feature or just upload videos to YouTube and add this feature at the end of the year, when all projects from this year have videos. 

We should upload them to our YouTube account first. (Ask us where you can find credentials)

==
Where To App:
https://drive.google.com/file/d/19B46QSgN9J2S8dnfBrwq4y8tzMRCWZtB/view
Tech Start Website:
https://drive.google.com/drive/folders/1IhwVs9DNHa0KUoliDvAVvwGRhSQdSKG1

**Comment by Jhappy77** [comment]
Current plan: delay adding them to our website til we have more (later this year) but add them to YouTube

**Comment by Niyousha99** [comment]
Done
